[package]
name = "q"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = {version = "0.8.20"}
clap = { version = "4.5.13", features = ["derive"] }
anyhow = "1.0.95"
serde = { version = "1.0.217", features = ["derive"] }
